stages:
  - test
  - build
  - deploy
  - sast
  - analyze

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

active-job: #Active a test for install the dependencies
  stage: test
  image: node:21
  script: cd frontend && npm i

test-unitaire: #Active a test for unitary test
  stage: test
  image: node:21
  script:
    - npm install
    - npm run test

build-StockManager: #deploy and build the project
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"   # Définit l'emplacement du cache de la tâche d'analyse
    GIT_DEPTH: "0"   # Indique à git de récupérer toutes les branches du projet, requises par la tâche d'analyse
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -f frontend/Dockerfile -t $IMAGE_TAG frontend
    - docker push $IMAGE_TAG

sonarcloud-check: #For the clean code in the all the project
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - main

include:
  - template: Jobs/SAST.gitlab-ci.yml
    path: "frontend"
