sonar.projectKey = gaby134902_sonar 
sonar.organization = gaby134902
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}

# Il s'agit du nom et de la version affichés dans l'interface utilisateur de SonarCloud.
sonar.projectName=sonar
sonar.projectVersion=1.0


# Le chemin est relatif au fichier sonar-project.properties. Remplacez « \" » par « / » sous Windows.
sonar.sources=.

# Encodage du code source. La valeur par défaut est l'encodage système.
sonar.sourceEncoding=UTF-8